spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.example.org
    port: 587
    username: helicon@example.org
    password: testpassword
helicon:
  login:
    enable-login: true
    enable-registration: true
  order:
    allow-anonymous: true
    confirmation: true
    enable: true
  mail:
    notification:
      customer-on-order: true
      owner-on-order: true
      password-change: true
      registration: true
  assets: assets
  domain: markus-nentwich.at
