spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.example.org
    port: 587
    username: helicon@example.org
    password: testpassword
helicon:
  login:
    enable-login: true
    enable-registration: true
    root:
      enable: true
      password: test12345678
    jwt:
      expiration: 10
      issuer: helicon
      prefix: "Bearer "
  order:
    allow-anonymous: true
    confirmation: true
    enable: true
  mail:
    notification:
      customer-on-order: true
      owner-on-order: true
      password-change: true
      registration: true
  assets: assets
  bank:
    bic: RLNWATZUDJ
    iban: AT00 0000 0000 0000 0000
    name: Raika
  domain: markus-nentwich.at
