spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.example.org
    port: 587
    username: helicon@example.org
    password: testpassword
helicon:
  login:
    enable-login: true
    enable-registration: true
    root:
      enable: true
      password: test12345678
    jwt:
      expiration: 10
      issuer: helicon
      prefix: "Bearer "
  order:
    allow-anonymous: true
    confirmation: true
    enable: true
  mail:
    notification:
      customer-on-order: false
      owner-on-order: false
      password-change: false
      registration: false
    identity: Helicon Dev Mailer <helicon@markus-nentwich.at>
  assets: assets
  domain: markus-nentwich.at
  bill:
    name: Markus Nentwich
    iban: AT40 3209 2000 0025 8475
    bic: RLNWATWWGAE
    institute: Raiffeisen-Regionalbank
server:
  port: 2812
  servlet:
    context-path: /api/v1
springdoc:
  swagger-ui:
    path: /swagger.html
    url: /api/v1/api-docs
  api-docs:
    path: /api-docs