spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.example.org
    port: 587
    username: helicon@example.org
    password: testpassword
helicon:
  login:
    enable-login: true
    enable-registration: true
    root:
      enable: true
      password: test12345678
    jwt:
      expiration: 10
      issuer: helicon
      prefix: "Bearer "
  order:
    allow-anonymous: true
    confirmation: true
    enable: true
  mail:
    notification:
      customer-on-order: true
      owner-on-order: true
      password-change: true
      registration: true
  assets: assets
  domain: markus-nentwich.at
  bill:
    address:
      name: Markus Nentwich
      street: Vereinsgasse
      streetNumber: 25/14
      post-code: A-1020
      city: Wien
      mail: kontakt@markus-nentwich.at
      phone: +43699 / 10329882
    bank:
      name: Markus Nentwich
      iban: AT40 3209 2000 0025 8475
      bic: RLNWATWWGAE
      institute: Raiffeisen-Regionalbank
