
[.text-right]
{ownerName} +
{ownerStreet} {ownerStreetNumber} +
{ownerPostCode} {ownerCity} +
Telefon: {ownerPhone} +
E-Mail: {ownerEmail} +
Webseite: {ownerWebsite} +

ifdef::customerCompany[]
{company} +
endif::[]
{customerFirstname} {customerLastname} +
{customerStreet} {customerStreetNumber} +
{customerPostcode} {customerCity} +
{customerState} +

[.text-right]
{ownerCity}, am {billDate}

=== Rechnung Nr. {billNumber}

[cols="10,50,2*>20",options="header,footer"]
[frame=none, grid=rows]
|===
|Menge |Beschreibung |Einzelpreis |Gesamtpreis
|{amount} |{btitle} |€ {price} |€ {multiprice}
||Versand ({customerState})||€ {shipping}
|||Summe |€ {psum}
|===

Dieser Betrag enthält keine Umsatzsteuer aufgrund §6(2)27 Kleinunternehmerregelung.



Ich bitte Sie, den Betrag binnen 14 Tagen an das folgende Konto zu überweisen:

[cols="30h,70",frame="none",grid="none"]
|===
|Kontoname: |{bankName}
|IBAN: |{bankIban}
|BIC: |{bankBic}
|Geldinstitut: |{bankInstitute}
|Zahlungsreferenz: |{bankReference}
|===