= Rechnung_{billNumber}
:notitle:

[frame=none, grid=none, cols="<,>"]
|===
a|image::./images/verlag.svg[Static,250, opts=inline] | {ownerName} +
{ownerStreet} {ownerStreetNumber} +
{ownerPostCode} {ownerCity} +
Telefon: {ownerPhone} +
E-Mail: {ownerEmail} +
Webseite: {ownerWebsite}
|===

// billing and delivery address
ifdef::deliveryStreet[]
[frame=none, grid=none, cols="<,<"]
|===
s| Rechnungsadresse: s| Lieferadresse:
ifdef::customerCompany[]
a| {customerCompany} +
endif::[]
ifndef::customerCompany[]
a|
ifdef::customerSalutation[]
{customerSalutation} +
endif::[]
endif::[]
{customerFirstname} {customerLastname} +
{billingStreet} {billingStreetNumber} +
{billingPostcode} {billingCity} +
{billingState} a|
ifdef::customerSalutation[]
{customerSalutation} +
endif::[]
{customerFirstname} {customerLastname} +
{deliveryStreet} {deliveryStreetNumber} +
{deliveryPostcode} {deliveryCity} +
{deliveryState}
|===
endif::[]

// billing address only
ifndef::deliveryStreet[]
ifdef::customerCompany[]
{customerCompany} +
endif::[]
ifndef::customerCompany[]
ifdef::customerSalutation[]
{customerSalutation} +
endif::[]
endif::[]
{customerFirstname} {customerLastname} +
{billingStreet} {billingStreetNumber} +
{billingPostcode} {billingCity} +
{billingState} +
endif::[]

[.text-right]
{ownerCity}, am {billDate}

== Rechnung Nr. {billNumber}

[cols="^10,50,2*>20",options="header,footer"]
[frame=none, grid=rows, format=csv]
|===
include::{csvFile}[]
|===

[.text-center]
Dieser Betrag enthält keine Umsatzsteuer aufgrund §6(2)27 Kleinunternehmerregelung.

'''

Ich bitte Sie, den Betrag binnen 14 Tagen an das folgende Konto zu überweisen:
[cols="30h,70",frame="none",grid="none"]
|===
|Kontoname: |{bankName}
|IBAN: |{bankIban}
|BIC: |{bankBic}
|Geldinstitut: |{bankInstitute}
|Zahlungsreferenz: s|{bankReference}
|===

[.text-center]
*Im Feld Zahlungsreferenz unbedingt obige Nummer anführen, +
ansonsten kann die Zahlung nicht zugeordnet werden!*